// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJT1M_RYSo-kg6ZxCU1xZX67c11MdrMaQ',
    appId: '1:46240197229:web:d0affbbc7f6a292bc2ad64',
    messagingSenderId: '46240197229',
    projectId: 'food-inventory-system-firebase',
    authDomain: 'food-inventory-system-firebase.firebaseapp.com',
    storageBucket: 'food-inventory-system-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjagTjZOFa3Ro_M1qttBoH2_afTF5VmM',
    appId: '1:46240197229:android:f6f76a4f6d342bcdc2ad64',
    messagingSenderId: '46240197229',
    projectId: 'food-inventory-system-firebase',
    storageBucket: 'food-inventory-system-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbHjCgN7ct11n20l73uqdKIvZALfI6Pfg',
    appId: '1:46240197229:ios:d51a3a96f86fe380c2ad64',
    messagingSenderId: '46240197229',
    projectId: 'food-inventory-system-firebase',
    storageBucket: 'food-inventory-system-firebase.firebasestorage.app',
    iosBundleId: 'com.example.foodInventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbHjCgN7ct11n20l73uqdKIvZALfI6Pfg',
    appId: '1:46240197229:ios:d51a3a96f86fe380c2ad64',
    messagingSenderId: '46240197229',
    projectId: 'food-inventory-system-firebase',
    storageBucket: 'food-inventory-system-firebase.firebasestorage.app',
    iosBundleId: 'com.example.foodInventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJT1M_RYSo-kg6ZxCU1xZX67c11MdrMaQ',
    appId: '1:46240197229:web:5dc75dab3dd6f5cbc2ad64',
    messagingSenderId: '46240197229',
    projectId: 'food-inventory-system-firebase',
    authDomain: 'food-inventory-system-firebase.firebaseapp.com',
    storageBucket: 'food-inventory-system-firebase.firebasestorage.app',
  );
}
